### ISSUE TITLE
Validate user input for username field when sign up

### ISSUE THREAD

**Issue by tehseen01** [tehseen01/instagram-clone#2]
As a developer, I want to prevent the user from entering invalid characters in the username field, such as uppercase letters, space and special symbols other than - and _ . This would ensure the consistency and security of the user data.

### Acceptance criteria:

- The username field should only accept lowercase letters, numbers, hyphens, dot and underscores
- The username field should display an error message if the user enters any invalid character
- The username field should not allow the user to submit the form until the error is resolved

![Screenshot 2023-05-19 105208](https://github.com/tehseen01/instagram-clone/assets/86504467/4b6c0847-0472-4aea-9e82-b258d20879e3)

**Comment by bonapartbon** [comment]
@tehseen01 can i work on this issue?

**Comment by tehseen01** [comment]
Sure, feel free to work on this issue. Please make sure to follow the contribution guidelines and check for any updates before submitting your pull request

**Comment by bonapartbon** [comment]
@tehseen01 i have some problems when running this repo, it stucks at 404 page.

**Comment by bonapartbon** [comment]
> Sure, feel free to work on this issue. Please make sure to follow the contribution guidelines and check for any updates before submitting your pull request

yes just saw you update README. thanks

**Comment by tehseen01** [comment]
if you have not setup backend then you will see 404 error

**Comment by tehseen01** [comment]
if you don't want to setup backend then simply you can just paste this url in the `.env` file 
```
NEXT_PUBLIC_API_URL= https://social-api-three.vercel.app/api/
```

**Comment by bonapartbon** [comment]
@tehseen01 i pushed into my fork but when i click compare & pull request. this shows up. 
<img width="953" alt="Screenshot 2023-05-20 at 1 33 23 PM" src="https://github.com/tehseen01/instagram-clone/assets/64571759/a82a6bb3-04f4-498a-807f-1c9678bbf585">
